
[folders]
data_folder_path="/home/steve/Data/MDR source data/NHS Org Data/2025 October/"
log_folder_path="/home/steve/Data/MDR/MDR_Logs/nhs/"

[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port="5432"
db_name="nhs"
